site_name: Wiki Trip
site_description: Wiki Insight！
site_author: Yuchen
# site_url: https://squidfunk.github.io/mkdocs-material/

# Repository
# repo_name: yuchen-sun/docker-journey
# repo_url: https://github.com/yuchen-sun/docker-journey
# edit_uri: ""

# Copyright
copyright: 'Yuchen'

# Configuration
theme:
  name: material
  language: zh
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png

extra_css:
  - css/styles.css
  - css/dark-mode.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/yuchen-sun/docker-journey

# Extensions
markdown_extensions:
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dockersamples
      repo: 101-tutorial
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

# Page tree
nav:
  - README: trip/index.md
  - Docker: 
    - 提纲: trip/container/README.md
    - 安装Docker: 
      - Mac/Windows: trip/container/install/win-mac.md
      - Linux: trip/container/install/linux.md
    - 容器: 
      - 运行你的第一个容器: trip/container/tutorials/run.md
      - medium 容器，进程，虚拟机: trip/container/containers/container-process-vm.md
    - 容器镜像: 
      - medium 镜像的含义: trip/container/images/images.md
  - Lustre:
    - 安装Lustre:
      - 简易版: trip/lustre/install/install.md
